/**
 * @file    board.h
 * @brief   STM32L0538-DISCO board support: user LEDs, user button and
 *          ST-LINK virtual COM port logging.
 *
 * GPIO configuration for the LEDs and the button is generated by CubeMX
 * (MX_GPIO_Init); this module only provides access helpers.
 */
#ifndef BOARD_H
#define BOARD_H

/* Includes -----------------------------------------------------------------*/
#include <stdbool.h>

/* Exported functions prototypes --------------------------------------------*/

/** @brief Switch the green user LED (LD3, PB4). */
void board_led_green(bool on);

/** @brief Switch the red user LED (LD4, PA5). */
void board_led_red(bool on);

/** @brief Read the user button B1 (PA0). @return true while pressed (pin high). */
bool board_button_pressed(void);

/**
 * @brief Arm wake-up from STOP mode on the rising edge of B1 (EXTI0).
 *
 * The EXTI line is only enabled around STOP entry. Call
 * board_disarm_wake() after waking to restore B1 as a plain input.
 */
void board_arm_wake(void);

/** @brief Disable the B1 wake-up interrupt and restore PA0 as a plain input. */
void board_disarm_wake(void);

/** @brief Return true once the B1 wake-up interrupt has fired since board_arm_wake(). */
bool board_wake_flag(void);

/**
 * @brief printf-style logging over USART1 (ST-LINK virtual COM port).
 *
 * Output is terminated with "\r\n" and truncated to 93 characters.
 * Serial settings: 115200 baud, 8N1. The board solder bridges SB2 and SB3
 * must be closed to route USART1 to the ST-LINK (default on newer board
 * revisions).
 */
void board_log(const char *fmt, ...);

#endif /* BOARD_H */
