/**
 * @file    app.c
 * @brief   Showcase application for the STM32L0538-DISCO.
 *
 * A menu on the e-paper display gives access to demonstrations of:
 *   - the e-paper display itself (it holds its image without power)
 *   - the linear touch sensor (TSC)
 *   - the user button B1 and the user LEDs LD3 / LD4
 *   - ultra-low-power STOP mode (display unpowered, wake-up on B1)
 *   - ST-LINK virtual COM port logging (USART1)
 *   - 4-level and multi-pass gray rendering
 *   - experimental fast-refresh modes and a panel recovery routine
 *
 * Input:
 *   B1 short press : next item / action
 *   B1 long press  : select / back
 *   Touch strip    : on pages other than the menu, left = back and
 *                    middle / right = action or next (depending on the page)
 *
 * A full e-paper refresh blocks for a couple of seconds; input pressed during
 * a refresh is ignored.
 */

/* Includes -----------------------------------------------------------------*/
#include "app.h"
#include "board.h"
#include "epaper.h"
#include "gfx.h"
#include "touch.h"
#include "main.h"
#include <stdio.h>
#include <string.h>

/* Private function prototypes ----------------------------------------------*/
extern void SystemClock_Config(void);      /* generated by CubeMX in main.c */

/* Private typedef ----------------------------------------------------------*/
typedef enum { PAGE_MENU, PAGE_TOUCH, PAGE_LEDS, PAGE_STOP, PAGE_INFO, PAGE_DISPTEST, PAGE_MAXFPS, PAGE_EXTREMEFPS, PAGE_EXTREMEGFX, PAGE_RECOVERY } page_t;
typedef enum { EV_NONE, EV_SHORT, EV_LONG, EV_LEFT, EV_MID, EV_RIGHT } event_t;

/* Private defines ----------------------------------------------------------*/
#define APP_LONG_PRESS_MS         700U     /* B1 press duration that counts as a long press */
#define APP_BUTTON_DEBOUNCE_MS     30U     /* B1 presses shorter than this are ignored */
#define APP_TOUCH_POLL_MS          20U     /* interval between touch scans */
#define APP_TOUCH_REDRAW_MS      1000U     /* minimum gap between touch-page refreshes */
#define APP_FPS_BUSY_TIMEOUT_MS  5000U     /* max wait for one fast-refresh frame */
#define APP_STOP_DISABLE_DEBUG      1      /* lowest STOP current (the debugger disconnects in STOP) */
#define APP_STOP_ULTRA_LOW_POWER    1      /* ultra-low-power mode and fast wake-up in STOP */

#define RECOVERY_CYCLES 8U                 /* black + white refresh pairs, see run_recovery() */
#define MAXFPS_WINDOW_FRAMES 4U            /* frames averaged per FPS reading */

/* Private variables --------------------------------------------------------*/

/* Menu entries and the page each one opens. */
#define MENU_COUNT 9U
static const char *const menu_text[MENU_COUNT] = {
  "Touch sensor", "LEDs & button", "Low power (STOP)", "System info", "Display test",
  "Maximum Framerate", "Extreme FPS", "Extreme Graphics", "Panel Recovery"
};
static const page_t menu_page[MENU_COUNT] = {
  PAGE_TOUCH, PAGE_LEDS, PAGE_STOP, PAGE_INFO, PAGE_DISPTEST, PAGE_MAXFPS, PAGE_EXTREMEFPS, PAGE_EXTREMEGFX,
  PAGE_RECOVERY
};

static page_t  page = PAGE_MENU;
static uint8_t sel;
static bool    redraw;
static bool    touch_ok;
static uint8_t led_mode;                  /* 0 off, 1 green, 2 red, 3 both */
static int8_t  shown_zone = -2;

/* Display test stage: 0 = Example 1 (B/W), 1 = Example 2 (4-gray),
 * 2 = Example 3 (dithered 16-gray), 3 = Example 4 (dithered gradient),
 * 4 = Example 5 (16 solid levels), 5 = Example 6 (smooth gradient).
 * Examples 3/4 are explained above dither_color(), Examples 5/6 above g16_state_t. */
static uint8_t disp_stage;
#define DISP_STAGE_COUNT 6U
static uint32_t last_touch_draw;

/* Private functions --------------------------------------------------------*/

/* Unrecoverable error: blink the red LED fast and repeat a message on the
 * virtual COM port. A typical cause is a wrong EPAPER_DISPLAY setting. */
static void fatal(const char *msg)
{
  uint32_t n = 0;
  for (;;)
  {
    if ((n++ % 20U) == 0U) board_log("ERROR: %s (EPAPER_DISPLAY=%u, %s)",
                                     msg, epaper_display_id(), epaper_name());
    board_led_red(true);  HAL_Delay(100);
    board_led_red(false); HAL_Delay(100);
  }
}

static void show(void)                    /* push framebuffer to the panel */
{
  if (!epaper_update()) fatal("e-paper BUSY timeout - wrong display selected?");
}

/* Drawing ------------------------------------------------------------------*/

/* Text scale of titles and menu entries: 2 on the larger display. */
static uint8_t ui_scale(void) { return (epaper_height() >= 100U) ? 2U : 1U; }

static void draw_title(const char *t)
{
  uint8_t  s = ui_scale();
  uint16_t h = (uint16_t)(GFX_CHAR_H * s + 2U);
  epaper_fill_rect(0, 0, epaper_width(), h, EPAPER_BLACK);
  gfx_text(3, 2, t, s, EPAPER_WHITE);
}

static void draw_footer(const char *t)
{
  gfx_text(2, (uint16_t)(epaper_height() - 9U), t, 1, EPAPER_BLACK);
}

/* Word-wrap body text to max_w pixels, using gfx_text_width() for measuring.
 * Drawing stops at max_y instead of running past the bottom of the screen;
 * callers keep their text short enough to fit the smaller display. */
static void draw_wrapped(uint16_t x, uint16_t y, uint16_t max_w, uint16_t max_y, const char *text)
{
  uint16_t    lh = (uint16_t)(GFX_CHAR_H + 2U);
  char        line[64];
  size_t      len = 0;
  const char *p = text;

  line[0] = '\0';
  while (*p != '\0' && y <= max_y)
  {
    while (*p == ' ') p++;
    const char *we = p;
    while (*we != '\0' && *we != ' ') we++;
    size_t wlen = (size_t)(we - p);
    if (wlen == 0U) break;
    if (wlen >= sizeof(line)) wlen = sizeof(line) - 1U;

    char trial[64];
    if (len == 0U) snprintf(trial, sizeof(trial), "%.*s", (int)wlen, p);
    else           snprintf(trial, sizeof(trial), "%s %.*s", line, (int)wlen, p);

    if (len != 0U && gfx_text_width(trial, 1) > max_w)
    {
      gfx_text(x, y, line, 1, EPAPER_BLACK);
      y = (uint16_t)(y + lh);
      snprintf(line, sizeof(line), "%.*s", (int)wlen, p);
      len = strlen(line);
    }
    else
    {
      strncpy(line, trial, sizeof(line) - 1U);
      line[sizeof(line) - 1U] = '\0';
      len = strlen(line);
    }
    p = we;
  }
  if (len != 0U && y <= max_y) gfx_text(x, y, line, 1, EPAPER_BLACK);
}

static void draw_splash(void)
{
  char line[32];
  uint8_t s = ui_scale();
  epaper_clear(EPAPER_WHITE);
  epaper_rect(0, 0, epaper_width(), epaper_height(), EPAPER_BLACK);
  gfx_text_centered((uint16_t)(6U * s), "STM32L0538-DISCO", s, EPAPER_BLACK);
  gfx_text_centered((uint16_t)(6U * s + 10U * s), epaper_name(), 1, EPAPER_BLACK);
  snprintf(line, sizeof(line), "EPAPER_DISPLAY = %u", (unsigned)epaper_display_id());
  gfx_text_centered((uint16_t)(6U * s + 10U * s + 12U), line, 1, EPAPER_BLACK);
  gfx_text_centered((uint16_t)(epaper_height() - 14U), "Starting...", 1, EPAPER_BLACK);
}

/* Main menu: a vertically scrolling list. The row height is fixed; only as many
 * items as fit are shown, and the visible window follows `sel`. The window is
 * recomputed from `sel` on every draw, so no scroll offset has to be stored:
 * `sel` moves by one item at a time. */
static void draw_menu(void)
{
  uint8_t  s   = ui_scale();
  uint16_t lh  = (uint16_t)(GFX_CHAR_H * s + 1U);          /* fixed row height */
  uint16_t y0  = (uint16_t)(GFX_CHAR_H * s + 5U);
  uint16_t room = (uint16_t)(epaper_height() - 9U - y0);   /* space above the footer line */

  uint8_t visible = (uint8_t)(room / lh);                  /* items that actually fit */
  if (visible < 1U) visible = 1U;

  /* Smallest scroll offset that keeps `sel` inside the visible window. */
  uint8_t top = (uint8_t)((sel >= visible) ? (sel - visible + 1U) : 0U);
  uint8_t last = (uint8_t)(top + visible);
  if (last > MENU_COUNT) last = MENU_COUNT;

  bool     scrollable = (MENU_COUNT > visible);
  uint16_t sb_w  = scrollable ? 4U : 0U;      /* reserve a thin column for the scrollbar */
  uint16_t row_w = (uint16_t)(epaper_width() - sb_w);

  draw_title("STM32L0538-DISCO");
  for (uint8_t i = top; i < last; i++)
  {
    uint16_t y = (uint16_t)(y0 + (i - top) * lh);
    if (i == sel)
    {
      epaper_fill_rect(0, (uint16_t)(y - 1U), row_w, lh, EPAPER_BLACK);
      gfx_text(6, y, menu_text[i], s, EPAPER_WHITE);
    }
    else
    {
      gfx_text(6, y, menu_text[i], s, EPAPER_BLACK);
    }
  }

  if (scrollable)
  {
    /* Scroll indicator: a thin track spanning the list area and a thumb
     * showing which slice of the MENU_COUNT items is visible. */
    uint16_t track_x = (uint16_t)(epaper_width() - 2U);
    epaper_vline(track_x, y0, room, EPAPER_BLACK);

    uint16_t thumb_h = (uint16_t)(((uint32_t)room * visible) / MENU_COUNT);
    if (thumb_h < 3U) thumb_h = 3U;
    uint16_t travel   = (uint16_t)(room - thumb_h);
    uint16_t thumb_y  = (uint16_t)(y0 + ((uint32_t)travel * top) / (uint16_t)(MENU_COUNT - visible));
    epaper_fill_rect((uint16_t)(track_x - 1U), thumb_y, 3, thumb_h, EPAPER_BLACK);
  }

  draw_footer("B1: move  hold: select");
}

static void draw_touch(void)
{
  const touch_state_t *t = touch_state();
  char line[32];
  uint16_t W = epaper_width(), H = epaper_height();
  uint16_t top = (uint16_t)(GFX_CHAR_H * ui_scale() + 5U);
  uint16_t h   = (uint16_t)(H - top - 33U);
  uint16_t bw  = (uint16_t)((W - 8U - 2U * 4U) / 3U);

  draw_title("Touch sensor");
  for (uint8_t i = 0; i < 3; i++)
  {
    uint16_t x = (uint16_t)(4U + i * (bw + 4U));
    if (t->zone == (int8_t)i) epaper_fill_rect(x, top, bw, h, EPAPER_BLACK);
    else                      epaper_rect(x, top, bw, h, EPAPER_BLACK);
  }
  if (touch_ok)
  {
    snprintf(line, sizeof(line), "raw  %u %u %u", t->raw[0], t->raw[1], t->raw[2]);
    gfx_text(2, (uint16_t)(top + h + 3U), line, 1, EPAPER_BLACK);
    snprintf(line, sizeof(line), "base %u %u %u", t->base[0], t->base[1], t->base[2]);
    gfx_text(2, (uint16_t)(top + h + 12U), line, 1, EPAPER_BLACK);
  }
  else
  {
    gfx_text(2, (uint16_t)(top + h + 3U),  "No TSC counts. Check CubeMX", 1, EPAPER_BLACK);
    gfx_text(2, (uint16_t)(top + h + 12U), "TSC groups / IO roles.", 1, EPAPER_BLACK);
  }
  draw_footer("Touch the sensor. B1: back");
  shown_zone = t->zone;
}

static void draw_leds(void)
{
  char line[32];
  draw_title("LEDs & button");
  uint16_t y = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  snprintf(line, sizeof(line), "LD3 green : %s", (led_mode & 1U) ? "ON" : "off");
  gfx_text(4, y, line, 1, EPAPER_BLACK);
  snprintf(line, sizeof(line), "LD4 red   : %s", (led_mode & 2U) ? "ON" : "off");
  gfx_text(4, (uint16_t)(y + 10U), line, 1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 24U), "B1 short press cycles them", 1, EPAPER_BLACK);
  draw_footer("B1: cycle LEDs   hold: back");
}

static void draw_stop_info(void)
{
  uint16_t y = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  draw_title("Low power (STOP)");
  gfx_text(4, y,                   "B1: sleep in STOP mode",  1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 10U), "Display is powered off",   1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 20U), "but keeps its image.",     1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 30U), "Wake: B1. Current: JP4.",  1, EPAPER_BLACK);
  draw_footer("B1: sleep   hold: back");
}

static void draw_info(void)
{
  char line[32];
  uint16_t y = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  draw_title("System info");
  snprintf(line, sizeof(line), "Disp: %s", epaper_name());
  gfx_text(2, y, line, 1, EPAPER_BLACK);
  snprintf(line, sizeof(line), "EPAPER_DISPLAY = %u", (unsigned)epaper_display_id());
  gfx_text(2, (uint16_t)(y + 9U), line, 1, EPAPER_BLACK);
  snprintf(line, sizeof(line), "SYSCLK: %lu MHz", (unsigned long)(HAL_RCC_GetSysClockFreq() / 1000000UL));
  gfx_text(2, (uint16_t)(y + 18U), line, 1, EPAPER_BLACK);
  snprintf(line, sizeof(line), "Uptime: %lu s", (unsigned long)(HAL_GetTick() / 1000UL));
  gfx_text(2, (uint16_t)(y + 27U), line, 1, EPAPER_BLACK);
  snprintf(line, sizeof(line), "Touch: %s", touch_ok ? "OK" : "not working");
  gfx_text(2, (uint16_t)(y + 36U), line, 1, EPAPER_BLACK);
  draw_footer("Any press: back");
}

static void draw_maxfps_intro(void)
{
  uint16_t y = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  draw_title("Maximum Framerate");
  gfx_text(4, y,                    "Experimental: updates the panel",  1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 10U),  "as fast as it will go, using a",   1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 20U),  "custom short waveform. Bars flip", 1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 30U),  "every frame; contrast drops as",   1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 40U),  "speed rises. FPS shown on screen.", 1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 54U),  "Running: B1/touch = faster level", 1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(y + 64U),  "hold B1 = stop and go back",       1, EPAPER_BLACK);
  draw_footer("B1: start   hold: back");
}

static void draw_extremefps_intro(void)
{
  uint16_t y     = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  uint16_t max_w = (uint16_t)(epaper_width() - 8U);
  uint16_t max_y = (uint16_t)(epaper_height() - 11U);
  draw_title("Extreme FPS");
  draw_wrapped(4, y, max_w, max_y,
    "SPI at 16MHz, past spec. Skips RED-RAM write. Contrast/link may "
    "suffer. B1 cycles level while running.");
  draw_footer("B1: start   hold: back");
}

static void draw_extremegfx_intro(void)
{
  uint16_t y     = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  uint16_t max_w = (uint16_t)(epaper_width() - 8U);
  uint16_t max_y = (uint16_t)(epaper_height() - 11U);
  draw_title("Extreme Graphics");
  draw_wrapped(4, y, max_w, max_y,
    "Same fast refresh as Extreme FPS, drawing shapes/text/counter/box. "
    "B1 cycles level while running.");
  draw_footer("B1: start   hold: back");
}

static void draw_recovery_intro(void)
{
  uint16_t y     = (uint16_t)(GFX_CHAR_H * ui_scale() + 6U);
  uint16_t max_w = (uint16_t)(epaper_width() - 8U);
  uint16_t max_y = (uint16_t)(epaper_height() - 11U);
  draw_title("Panel Recovery");
  draw_wrapped(4, y, max_w, max_y,
    "Runs full black/white refresh cycles (normal, in-spec waveform) -- "
    "the standard ghosting fix. Hold B1 to cancel.");
  draw_footer("B1: start   hold: back");
}

/* The display-test example drawers are defined further down, next to the
 * helpers they share. */
static void draw_example1_basic(void);
static void draw_example2_4gray(void);
static void draw_example3_16gray(void);
static void draw_example4_gradient(void);
static void draw_example5_16smooth(void);
static void draw_example6_smooth(void);

static void draw_page(void)
{
  epaper_clear(EPAPER_WHITE);
  switch (page)
  {
    case PAGE_MENU:     draw_menu();                 break;
    case PAGE_TOUCH:    draw_touch();                break;
    case PAGE_LEDS:     draw_leds();                 break;
    case PAGE_STOP:     draw_stop_info();            break;
    case PAGE_INFO:     draw_info();                 break;
    case PAGE_DISPTEST: draw_example1_basic();       break;  /* stage 0 only */
    case PAGE_MAXFPS:   draw_maxfps_intro();         break;
    case PAGE_EXTREMEFPS: draw_extremefps_intro();   break;
    case PAGE_EXTREMEGFX: draw_extremegfx_intro();   break;
    case PAGE_RECOVERY: draw_recovery_intro();       break;
  }
}

/* Display test: Example 1 - Basic (B/W) -------------------------------------
 *
 * Exercises the drawing API (epaper_* primitives and gfx_* text) on one screen:
 * two font sizes, a line, an outline rectangle, a filled rectangle with a fine
 * checkerboard cut out of it, a hollow and a filled circle, and a diagonal
 * crossing all of them. Rendered in plain B/W with epaper_update().
 */
static void draw_example1_basic(void)
{
  uint16_t w = epaper_width(), h = epaper_height();
  uint8_t  s = ui_scale();
  uint16_t top = (uint16_t)(GFX_CHAR_H * s + 5U);

  draw_title("Example 1 - Basic");

  /* Font sizes: the same string at two scales (fixed 5x7 font, integer scaled). */
  gfx_text(2, top, "Aa1", 1, EPAPER_BLACK);
  gfx_text((uint16_t)(2U + gfx_text_width("Aa1 ", 1)), top, "Aa1", 2, EPAPER_BLACK);

  uint16_t y0       = (uint16_t)(top + GFX_CHAR_H * 2U + 4U);
  uint16_t footer_y = (uint16_t)(h - 9U);
  uint16_t ch       = (footer_y > (uint16_t)(y0 + 6U)) ? (uint16_t)(footer_y - y0 - 2U) : 6U;
  uint16_t cellw    = (uint16_t)(w / 4U);

  epaper_hline(2, y0, (uint16_t)(w - 4U), EPAPER_BLACK);
  epaper_rect(0, (uint16_t)(y0 + 2U), w, ch, EPAPER_BLACK);

  uint16_t iw = (uint16_t)(cellw - 6U), ih = (uint16_t)(ch - 6U);
  uint16_t iy = (uint16_t)(y0 + 5U);

  /* Cell 0: outline rectangle. */
  epaper_rect(3U, iy, iw, ih, EPAPER_BLACK);

  /* Cell 1: filled rectangle with a fine checkerboard punched into it. */
  uint16_t x1 = (uint16_t)(3U + cellw);
  epaper_fill_rect(x1, iy, iw, ih, EPAPER_BLACK);
  for (uint16_t yy = 0; yy < ih; yy += 2U)
    for (uint16_t xx = 0; xx < iw; xx += 2U)
      if (((xx / 2U + yy / 2U) & 1U) == 0U)
        epaper_set_pixel((uint16_t)(x1 + xx), (uint16_t)(iy + yy), EPAPER_WHITE);

  /* Cell 2: hollow circle, cell 3: filled circle. */
  uint16_t rad = (uint16_t)((iw < ih ? iw : ih) / 2U);
  if (rad < 3U) rad = 3U;
  uint16_t cx2 = (uint16_t)(3U + 2U * cellw + iw / 2U);
  uint16_t cy  = (uint16_t)(iy + ih / 2U);
  epaper_circle(cx2, cy, rad, EPAPER_BLACK);
  uint16_t cx3 = (uint16_t)(3U + 3U * cellw + iw / 2U);
  epaper_fill_circle(cx3, cy, rad, EPAPER_BLACK);

  /* Diagonal across the whole content band, drawn last so it crosses the shapes. */
  for (uint16_t x = 0; x < w; x++)
  {
    uint16_t yy = (uint16_t)(y0 + 2U + ((uint32_t)x * (ch - 1U)) / (w - 1U));
    epaper_set_pixel(x, yy, EPAPER_BLACK);
  }

  draw_footer("B1/touch: next   hold: menu");
}

/* Display test: Example 2 - 4-level grayscale ------------------------------
 *
 * Four large swatches in the native shades (white, light gray, dark gray,
 * black), each holding a digit drawn in the opposite shade to show text and
 * shapes at a non-default gray value, plus a small ramp strip showing the
 * black-to-white transition across the four levels.
 * epaper_update_gray() calls this twice per refresh (once per shade bit), so
 * it only draws and keeps no state of its own.
 */
static void draw_example2_4gray(void)
{
  static const uint8_t shade[4]    = { EPAPER_WHITE, EPAPER_GRAY_LIGHT, EPAPER_GRAY_DARK, EPAPER_BLACK };
  static const uint8_t ramp[4]     = { EPAPER_BLACK, EPAPER_GRAY_DARK, EPAPER_GRAY_LIGHT, EPAPER_WHITE };
  static const char *const name[4] = { "WHITE", "LIGHT", "DARK", "BLACK" };
  uint16_t W = epaper_width(), H = epaper_height();
  uint16_t top      = (uint16_t)(GFX_CHAR_H * ui_scale() + 5U);
  uint16_t footer_y = (uint16_t)(H - 9U);
  uint16_t avail    = (uint16_t)(footer_y - top);
  uint16_t cap_h    = 9U;
  uint16_t strip_h  = (avail >= 60U) ? 10U : 6U;
  uint16_t h        = (uint16_t)(avail - cap_h - strip_h - 5U);   /* main swatch height */
  uint16_t bw       = (uint16_t)((W - 8U - 3U * 4U) / 4U);

  epaper_clear(EPAPER_WHITE);
  draw_title("Example 2 - 4 Gray");
  for (uint8_t i = 0; i < 4; i++)
  {
    uint16_t x  = (uint16_t)(4U + i * (bw + 4U));
    uint16_t tw = gfx_text_width(name[i], 1);
    epaper_fill_rect(x, top, bw, h, shade[i]);
    epaper_rect(x, top, bw, h, EPAPER_BLACK);

    /* Digit drawn in the opposite shade, so it is visible on any swatch. */
    char idx[2] = { (char)('0' + i), 0 };
    epaper_fill_rect((uint16_t)(x + bw / 2U - 4U), (uint16_t)(top + h / 2U - 5U), 8, 10, shade[3U - i]);
    gfx_text((uint16_t)(x + bw / 2U - 2U), (uint16_t)(top + h / 2U - 4U), idx, 1, shade[i]);

    gfx_text((uint16_t)(x + (bw - tw) / 2U), (uint16_t)(top + h + 3U), name[i], 1, EPAPER_BLACK);
  }

  /* Transition strip: the same four levels, black to white from left to right. */
  uint16_t sy = (uint16_t)(top + h + 3U + cap_h + 2U);
  for (uint8_t i = 0; i < 4; i++)
    epaper_fill_rect((uint16_t)(4U + i * (bw + 4U)), sy, bw, strip_h, ramp[i]);

  draw_footer("Any press: next   hold: menu");
}

/* Dithering shared by Examples 3 and 4 --------------------------------------
 *
 * Each pixel of a gray refresh is driven to one of 4 states: both panels'
 * RAM holds 2 bits per pixel, and on the GDEY0213B74 (SSD1680) those 2 bits
 * select 1 of 4 waveform LUT entries (see ssd1680_gray4_lut and
 * panel_gray_plane_done() in epaper.c). A single refresh cannot produce more
 * than 4 optical states per pixel.
 *
 * In-between levels are approximated by spatial dithering of the four native
 * shades. A 4x4 ordered (Bayer) matrix mixes the two nearest native shades
 * pixel by pixel, so a small tile's average reflectance approximates the
 * requested level. Over the 3 gaps between the 4 shades this gives
 * 3 * 16 + 1 = 49 target brightnesses, at the cost of spatial resolution.
 * Every dithered pixel is really driven to one of the panel's 4 states, and
 * the refresh is the regular epaper_update_gray() waveform.
 */
#define DITHER_STEPS   16U
#define DITHER_LEVELS  48U   /* 3 gaps between the 4 native shades * 16 steps */

static const uint8_t dither_bayer4x4[4][4] = {
  {  0,  8,  2, 10 },
  { 12,  4, 14,  6 },
  {  3, 11,  1,  9 },
  { 15,  7, 13,  5 }
};

/* level: 0 (black) .. DITHER_LEVELS (white). Returns the EPAPER_* shade to
 * plot at (x, y) so that a 4x4 tile's average approximates `level`. */
static uint8_t dither_color(uint16_t x, uint16_t y, uint16_t level)
{
  static const uint8_t shade[4] = { EPAPER_BLACK, EPAPER_GRAY_DARK, EPAPER_GRAY_LIGHT, EPAPER_WHITE };
  if (level > DITHER_LEVELS) level = DITHER_LEVELS;
  uint8_t gap = (uint8_t)(level / DITHER_STEPS);
  if (gap > 2U) gap = 2U;
  uint8_t frac = (uint8_t)(level - (uint16_t)gap * DITHER_STEPS);   /* 0..16 */
  uint8_t thr  = dither_bayer4x4[y & 3U][x & 3U];                   /* 0..15 */
  return shade[(frac > thr) ? (uint8_t)(gap + 1U) : gap];
}

/* Display test: Example 3 - dithered 16-level grayscale ---------------------
 *
 * 16 vertical bands, each dithered to one of 16 evenly spaced target
 * brightnesses and labelled 0-F (one character per band fits even on the
 * narrow GDE021A1). A second strip below shows the same 16 values in a
 * shuffled order, so that contrast illusions on the ordered strip cannot be
 * mistaken for distinguishable levels.
 */
static void draw_example3_16gray(void)
{
  uint16_t w = epaper_width(), h = epaper_height();
  uint8_t  s = ui_scale();
  uint16_t top      = (uint16_t)(GFX_CHAR_H * s + 5U);
  uint16_t footer_y = (uint16_t)(h - 9U);
  static const char    hexd[16]    = "0123456789ABCDEF";
  static const uint8_t shuffle[16] = { 0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15 };

  epaper_clear(EPAPER_WHITE);
  draw_title("Example 3 - 16 Gray");

  uint16_t bandw   = (uint16_t)((w - 4U) / 16U);
  uint16_t label_h = (uint16_t)(GFX_CHAR_H + 2U);
  uint16_t band_y  = (uint16_t)(top + label_h);
  uint16_t avail   = (uint16_t)(footer_y - band_y);
  uint16_t band_h  = (avail > 14U) ? (uint16_t)(avail - 12U) : 4U;
  uint16_t sec_y   = (uint16_t)(band_y + band_h + 2U);
  uint16_t sec_h   = (uint16_t)(footer_y - sec_y - 2U);

  for (uint8_t i = 0; i < 16U; i++)
  {
    uint16_t x     = (uint16_t)(2U + i * bandw);
    uint16_t level = (uint16_t)(((uint32_t)i * DITHER_LEVELS) / 15U);

    char lbl[2] = { hexd[i], 0 };
    gfx_text((uint16_t)(x + (bandw > 6U ? (bandw - 6U) / 2U : 0U)), top, lbl, 1, EPAPER_BLACK);

    for (uint16_t yy = 0; yy < band_h; yy++)
      for (uint16_t xx = 0; xx < bandw; xx++)
        epaper_set_pixel((uint16_t)(x + xx), (uint16_t)(band_y + yy),
                          dither_color((uint16_t)(x + xx), (uint16_t)(band_y + yy), level));

    uint16_t level2 = (uint16_t)(((uint32_t)shuffle[i] * DITHER_LEVELS) / 15U);
    for (uint16_t yy = 0; yy < sec_h; yy++)
      for (uint16_t xx = 0; xx < bandw; xx++)
        epaper_set_pixel((uint16_t)(x + xx), (uint16_t)(sec_y + yy),
                          dither_color((uint16_t)(x + xx), (uint16_t)(sec_y + yy), level2));
  }

  draw_footer("B1/touch: next   hold: menu");
}

/* Display test: Example 4 - dithered full-screen gradient -------------------
 *
 * A continuous black-to-white sweep across the whole content area, using the
 * dithering of Example 3 to reach the 49 effective steps described above
 * dither_color() instead of a plain 4-band ramp.
 */
static void draw_example4_gradient(void)
{
  uint16_t w = epaper_width(), h = epaper_height();
  uint8_t  s = ui_scale();
  uint16_t top      = (uint16_t)(GFX_CHAR_H * s + 5U);
  uint16_t footer_y = (uint16_t)(h - 9U);

  epaper_clear(EPAPER_WHITE);
  draw_title("Example 4 - Gradient");

  for (uint16_t y = top; y < footer_y; y++)
    for (uint16_t x = 0; x < w; x++)
    {
      uint16_t level = (uint16_t)(((uint32_t)x * DITHER_LEVELS) / (w - 1U));
      epaper_set_pixel(x, y, dither_color(x, y, level));
    }

  draw_footer("BLACK ---------------> WHITE");
}

/* Examples 5 and 6 - multi-pass gray ----------------------------------------
 *
 * Examples 3 and 4 mix the four native shades pixel by pixel. The native
 * shades are about 1/3 of the black-white range apart, so the mix is visible
 * as a pattern. Examples 5 and 6 use more native drive states instead, so
 * the remaining mixing is between nearly identical grays.
 *
 * A pixel gets a state n = 0..63, split into base-4 digits (weights 16, 4, 1)
 * that are applied over up to three refreshes, the 16s digit first (which
 * also resets the panel to white); see epaper_update_gray16() and
 * panel_gray16_lut() in epaper.c. Every n is a real per-pixel drive state.
 *
 * The brightness of each state was measured on a GDEY0213B74 by photographing
 * all 32 states (n = 0..31) as plain bands, twice, and averaging after scaling
 * both shots to the same black/white range. n is NOT monotonic in brightness:
 * the last refresh is much stronger per frame than the first, so n sorts into
 * a sawtooth. States whose last digit is 2 or 3 (a short final pulse) are
 * visibly grainy at mid-gray; that grain comes from the panel.
 *
 * Each table entry is {state n, brightness 0..255 (higher = lighter)}, chosen
 * from the 32 measured states by brightness, preferring the smoothest state
 * available at each step:
 *   g16_bands: the 16 bands of Example 5, darkest to lightest.
 *   g16_ramp:  the (more numerous) states that Example 6 interpolates between,
 *              so that neighbours are as close in brightness as the panel allows.
 * Both tables run out of smooth states at the light end (nothing measured
 * between n = 4 at 222 and white at 254), so the last step is the widest.
 *
 * To retune, photograph the 32 states again, repeat the measurement and edit
 * the numbers. Keep both tables sorted by brightness. The largest n in use (31)
 * sizes the waveform.
 */
typedef struct { uint8_t n; uint8_t b; } g16_state_t;
#define G16_LEVELS 16U
#define G16_RAMP_N 20U
static const g16_state_t g16_bands[G16_LEVELS] = {
  { 31,   0 }, { 30,  12 }, { 26,  27 }, { 15,  40 },
  { 29,  52 }, { 25,  71 }, { 21,  94 }, { 18, 103 },
  { 28, 124 }, { 24, 143 }, {  3, 156 }, { 12, 169 },
  {  8, 188 }, {  2, 212 }, {  4, 222 }, {  0, 254 }
};
static const g16_state_t g16_ramp[G16_RAMP_N] = {
  { 31,   0 }, { 27,   8 }, { 30,  12 }, { 26,  27 },
  { 15,  40 }, { 29,  52 }, { 19,  57 }, { 25,  71 },
  { 10,  77 }, { 21,  94 }, { 13,  99 }, { 28, 124 },
  {  9, 128 }, { 24, 143 }, {  3, 156 }, { 17, 167 },
  {  8, 188 }, { 16, 215 }, {  4, 222 }, {  0, 254 }
};

static uint8_t g16_max_frames(void)      /* largest n in use: sizes the waveform */
{
  uint8_t m = 0;
  for (uint8_t i = 0; i < G16_LEVELS; i++) if (g16_bands[i].n > m) m = g16_bands[i].n;
  for (uint8_t i = 0; i < G16_RAMP_N; i++) if (g16_ramp[i].n  > m) m = g16_ramp[i].n;
  return m;
}

/* Example 5: the layout of Example 3 (16 vertical bands labelled 0-F, 0 =
 * darkest, plus a shuffled strip below), without spatial dithering: every band
 * is one uniform drive state. */
static void draw_example5_16smooth(void)
{
  uint16_t w = epaper_width(), h = epaper_height();
  uint8_t  s = ui_scale();
  uint16_t top      = (uint16_t)(GFX_CHAR_H * s + 5U);
  uint16_t footer_y = (uint16_t)(h - 9U);
  static const char    hexd[16]    = "0123456789ABCDEF";
  static const uint8_t shuffle[16] = { 0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15 };

  epaper_clear(EPAPER_WHITE);
  draw_title("Example 5 - 16 Solid");

  uint16_t bandw   = (uint16_t)((w - 4U) / 16U);
  uint16_t label_h = (uint16_t)(GFX_CHAR_H + 2U);
  uint16_t band_y  = (uint16_t)(top + label_h);
  uint16_t avail   = (uint16_t)(footer_y - band_y);
  uint16_t band_h  = (avail > 14U) ? (uint16_t)(avail - 12U) : 4U;
  uint16_t sec_y   = (uint16_t)(band_y + band_h + 2U);
  uint16_t sec_h   = (uint16_t)(footer_y - sec_y - 2U);

  for (uint8_t i = 0; i < 16U; i++)
  {
    uint16_t x = (uint16_t)(2U + i * bandw);

    char lbl[2] = { hexd[i], 0 };
    gfx_text((uint16_t)(x + (bandw > 6U ? (bandw - 6U) / 2U : 0U)), top, lbl, 1, EPAPER_BLACK);

    epaper_fill_rect(x, band_y, bandw, band_h, EPAPER_FRAMES(g16_bands[i].n));
    epaper_fill_rect(x, sec_y,  bandw, sec_h,  EPAPER_FRAMES(g16_bands[shuffle[i]].n));
  }

  draw_footer("B1/touch: next   hold: menu");
}

/* Fine, irregular threshold 0..255 for Example 6 (integer form of
 * "interleaved gradient noise": frac(52.98 * frac(0.0671 x + 0.00584 y))).
 * Blue-noise-like, so it reads as grain instead of a grid or diagonals. */
static uint8_t g16_noise(uint16_t x, uint16_t y)
{
  uint32_t v = ((uint32_t)x * 4398U + (uint32_t)y * 383U) & 0xFFFFU;
  return (uint8_t)(((v * 53U) >> 8) & 0xFFU);
}

/* Example 6: black -> white across the full width, same layout as Example 4.
 * Each column's target is a brightness that rises linearly from the darkest
 * to the lightest entry of g16_ramp; the pixel takes one of the two ramp
 * states that bracket it, picked by g16_noise() in the right proportion. The
 * two candidates are neighbours in brightness, so the texture is only as
 * strong as the step between them (at most ~20 of 255 here; Example 4 mixes
 * shades ~70 apart). */
static void draw_example6_smooth(void)
{
  uint16_t w = epaper_width(), h = epaper_height();
  uint8_t  s = ui_scale();
  uint16_t top      = (uint16_t)(GFX_CHAR_H * s + 5U);
  uint16_t footer_y = (uint16_t)(h - 9U);
  int32_t  b_lo = g16_ramp[0].b, b_hi = g16_ramp[G16_RAMP_N - 1U].b;

  epaper_clear(EPAPER_WHITE);
  draw_title("Example 6 - Smooth");

  for (uint16_t x = 0; x < w; x++)
  {
    int32_t target = b_lo * 256 + ((b_hi - b_lo) * 256 * (int32_t)x) / (int32_t)(w - 1U);   /* 8.8 */
    uint8_t i = 0;
    while (i < G16_RAMP_N - 2U && target >= (int32_t)g16_ramp[i + 1U].b * 256) i++;

    int32_t lo   = (int32_t)g16_ramp[i].b * 256;
    int32_t span = (int32_t)g16_ramp[i + 1U].b * 256 - lo;
    int32_t frac = (span > 0) ? ((target - lo) * 256) / span : 0;   /* share of the lighter state */
    if (frac > 255) frac = 255;

    uint8_t dark  = g16_ramp[i].n;
    uint8_t light = g16_ramp[i + 1U].n;
    for (uint16_t y = top; y < footer_y; y++)
      epaper_set_pixel(x, y, EPAPER_FRAMES((frac > (int32_t)g16_noise(x, y)) ? light : dark));
  }

  draw_footer("BLACK ---------------> WHITE");
}

/* Input ---------------------------------------------------------------------*/

/* Poll B1 (short / long press, reported on release) and the touch sensor
 * (left / middle / right, reported once per touch). Returns EV_NONE if
 * nothing happened. */
static event_t input_poll(void)
{
  static bool     down;
  static uint32_t t_down, t_touch;
  static int8_t   last_zone = -1;
  uint32_t now = HAL_GetTick();

  bool p = board_button_pressed();
  if (p && !down) { down = true; t_down = now; }
  else if (!p && down)
  {
    down = false;
    uint32_t d = now - t_down;
    if (d >= APP_BUTTON_DEBOUNCE_MS) return (d >= APP_LONG_PRESS_MS) ? EV_LONG : EV_SHORT;
  }

  if (touch_ok && (now - t_touch) >= APP_TOUCH_POLL_MS)
  {
    t_touch = now;
    if (touch_scan())
    {
      int8_t z = touch_state()->zone;
      bool fresh = (z >= 0) && (last_zone < 0);
      last_zone = z;
      if (fresh) return (z == 0) ? EV_LEFT : (z == 1) ? EV_MID : EV_RIGHT;
    }
  }
  return EV_NONE;
}

/* Maximum Framerate (experimental) ------------------------------------------
 *
 * Alternates two bar patterns through the epaper_fast_*() path while showing
 * the achieved frame rate. B1 or touch selects the next (faster) level; a long
 * press or a touch on the left stops the test.
 */
/* Fill the framebuffer with the next frame: bars (memset, no per-pixel work)
 * plus a small readout box. Called while the panel is busy with the previous
 * frame, so its cost is hidden behind the refresh. */
static void maxfps_render(uint8_t phase, uint8_t level, uint32_t fps_x10)
{
  char txt[28];
  epaper_fast_pattern(phase);
  snprintf(txt, sizeof(txt), "L%u/%u N=%u  %lu.%lu fps",
           (unsigned)(level + 1U), (unsigned)EPAPER_FAST_LEVELS,
           (unsigned)epaper_fast_level_frames(level),
           (unsigned long)(fps_x10 / 10U), (unsigned long)(fps_x10 % 10U));
  uint16_t w = (uint16_t)(gfx_text_width(txt, 1) + 6U);
  epaper_fill_rect(4, 4, w, 13, EPAPER_WHITE);
  epaper_rect(4, 4, w, 13, EPAPER_BLACK);
  gfx_text(7, 8, txt, 1, EPAPER_BLACK);
}

static void run_maxfps(void)
{
  uint8_t  level = 0U, phase = 0U, win_frames = 0U;
  uint32_t win_t0, fps_x10 = 0U;
  bool     quit = false;

  if (!epaper_fast_begin())
  {
    board_log("maxfps: unavailable (GDEY0213B74 / EPAPER_DISPLAY=1 only) or BUSY timeout");
    epaper_fast_end();
    return;
  }
  board_log("maxfps: start, level 1/%u", (unsigned)EPAPER_FAST_LEVELS);

  maxfps_render(phase, level, fps_x10);
  win_t0 = HAL_GetTick();

  while (!quit)
  {
    epaper_fast_frame_start();                   /* send this frame, start refresh */
    phase ^= 1U;
    maxfps_render(phase, level, fps_x10);        /* next frame, drawn during the refresh */

    event_t  ev = EV_NONE;
    uint32_t t0 = HAL_GetTick();
    while (epaper_fast_busy())                   /* the one wait the panel needs */
    {
      event_t e = input_poll();
      if (e != EV_NONE) ev = e;
      if ((HAL_GetTick() - t0) > APP_FPS_BUSY_TIMEOUT_MS) fatal("e-paper BUSY timeout in max-fps test");
    }

    if (++win_frames >= MAXFPS_WINDOW_FRAMES)
    {
      uint32_t now = HAL_GetTick();
      uint32_t dt  = now - win_t0;
      if (dt == 0U) dt = 1U;
      fps_x10 = ((uint32_t)win_frames * 10000UL) / dt;
      board_log("maxfps: level %u/%u (N=%u): %lu.%lu fps",
                (unsigned)(level + 1U), (unsigned)EPAPER_FAST_LEVELS,
                (unsigned)epaper_fast_level_frames(level),
                (unsigned long)(fps_x10 / 10U), (unsigned long)(fps_x10 % 10U));
      win_frames = 0U;
      win_t0 = now;
    }

    if (ev == EV_LONG || ev == EV_LEFT)
    {
      quit = true;
    }
    else if (ev != EV_NONE)                      /* next (faster) level, wraps to level 1 */
    {
      level = (uint8_t)((level + 1U) % EPAPER_FAST_LEVELS);
      if (!epaper_fast_set_level(level)) fatal("e-paper BUSY timeout in max-fps test");
      fps_x10 = 0U;
      win_frames = 0U;
      win_t0 = HAL_GetTick();
    }
  }

  epaper_fast_end();                             /* normal SPI speed + full re-init on next update */
  board_log("maxfps: stopped");
}

/* Extreme FPS (experimental) -----------------------------------------------
 *
 * Same test as Maximum Framerate, driven through the epaper_extreme_*() path
 * (16 MHz SPI, B/W RAM only).
 */
static void extremefps_render(uint8_t phase, uint8_t level, uint32_t fps_x10)
{
  char txt[36];
  epaper_extreme_pattern(phase);
  snprintf(txt, sizeof(txt), "L%u/%u %lu MHz  %lu.%lu fps",
           (unsigned)(level + 1U), (unsigned)EPAPER_EXTREME_LEVELS,
           (unsigned long)(epaper_extreme_spi_hz() / 1000000UL),
           (unsigned long)(fps_x10 / 10U), (unsigned long)(fps_x10 % 10U));
  uint16_t w = (uint16_t)(gfx_text_width(txt, 1) + 6U);
  epaper_fill_rect(4, 4, w, 13, EPAPER_WHITE);
  epaper_rect(4, 4, w, 13, EPAPER_BLACK);
  gfx_text(7, 8, txt, 1, EPAPER_BLACK);
}

static void run_extremefps(void)
{
  uint8_t  level = 0U, phase = 0U, win_frames = 0U;
  uint32_t win_t0, fps_x10 = 0U;
  bool     quit = false;

  if (!epaper_extreme_begin())
  {
    board_log("extremefps: unavailable (GDEY0213B74 / EPAPER_DISPLAY=1 only) or BUSY timeout");
    epaper_extreme_end();
    return;
  }
  board_log("extremefps: start, level 1/%u", (unsigned)EPAPER_EXTREME_LEVELS);

  extremefps_render(phase, level, fps_x10);
  win_t0 = HAL_GetTick();

  while (!quit)
  {
    epaper_extreme_frame_start();                /* send this frame, start refresh */
    phase ^= 1U;
    extremefps_render(phase, level, fps_x10);    /* next frame, drawn during the refresh */

    event_t  ev = EV_NONE;
    uint32_t t0 = HAL_GetTick();
    while (epaper_extreme_busy())                /* the one wait the panel needs */
    {
      event_t e = input_poll();
      if (e != EV_NONE) ev = e;
      if ((HAL_GetTick() - t0) > APP_FPS_BUSY_TIMEOUT_MS) fatal("e-paper BUSY timeout in extreme-fps test");
    }

    if (++win_frames >= MAXFPS_WINDOW_FRAMES)
    {
      uint32_t now = HAL_GetTick();
      uint32_t dt  = now - win_t0;
      if (dt == 0U) dt = 1U;
      fps_x10 = ((uint32_t)win_frames * 10000UL) / dt;
      board_log("extremefps: level %u/%u (%lu MHz, N=%u): %lu.%lu fps",
                (unsigned)(level + 1U), (unsigned)EPAPER_EXTREME_LEVELS,
                (unsigned long)(epaper_extreme_spi_hz() / 1000000UL),
                (unsigned)epaper_extreme_level_frames(level),
                (unsigned long)(fps_x10 / 10U), (unsigned long)(fps_x10 % 10U));
      win_frames = 0U;
      win_t0 = now;
    }

    if (ev == EV_LONG || ev == EV_LEFT)
    {
      quit = true;
    }
    else if (ev != EV_NONE)                      /* next (faster) level, wraps to level 1 */
    {
      level = (uint8_t)((level + 1U) % EPAPER_EXTREME_LEVELS);
      if (!epaper_extreme_set_level(level)) fatal("e-paper BUSY timeout in extreme-fps test");
      fps_x10 = 0U;
      win_frames = 0U;
      win_t0 = HAL_GetTick();
    }
  }

  epaper_extreme_end();                          /* normal SPI speed + full re-init on next update */
  board_log("extremefps: stopped");
}

/* Extreme Graphics (experimental) ------------------------------------------
 *
 * Drives the panel through the same epaper_extreme_*() path as Extreme FPS,
 * but every frame is real drawing (rectangles, a circle, lines, a scrolling
 * text, a frame counter and a moving box) produced with the normal
 * epaper_*() / gfx_*() calls, instead of the flashing bars of
 * epaper_extreme_pattern().
 */

/* Triangle wave 0..range, taking `period` frames to rise and another `period`
 * to fall. Gives each animated element its own pace from the frame counter
 * alone, without per-element direction state. */
static uint16_t bounce_pos(uint32_t frame, uint16_t range, uint16_t period)
{
  if (period == 0U) period = 1U;
  uint32_t t = frame % (uint32_t)(2U * period);
  uint32_t d = (t <= period) ? t : (uint32_t)(2U * period - t);
  return (uint16_t)(((uint32_t)d * range) / period);
}

/* Fill the framebuffer with the next frame. Called while the panel is busy
 * with the previous frame, so its cost is hidden behind the refresh, as in
 * maxfps_render() / extremefps_render(). Every element moves at its own pace
 * (a different bounce_pos() period and phase each; the marquee scrolls), so
 * no pixel region stays at one state for the length of the test. */
static void extremegfx_render(uint32_t frame, uint16_t mx, uint32_t fps_x10)
{
  uint16_t w = epaper_width(), h = epaper_height();
  char     txt[36];
  static const char marquee[] = "EXTREME GRAPHICS -- STRESS TEST -- ";

  epaper_clear(EPAPER_WHITE);

  /* Status readout: the box of Maximum Framerate / Extreme FPS, showing the
   * frame counter. It also jitters by a few pixels on its own schedule. */
  snprintf(txt, sizeof(txt), "F=%lu  %lu.%lu fps",
           (unsigned long)frame, (unsigned long)(fps_x10 / 10U), (unsigned long)(fps_x10 % 10U));
  uint16_t tw    = (uint16_t)(gfx_text_width(txt, 1) + 6U);
  uint16_t box_x = (uint16_t)(4U + bounce_pos(frame, 3U, 13U));
  uint16_t box_y = (uint16_t)(4U + bounce_pos(frame + 7U, 3U, 19U));
  epaper_fill_rect(box_x, box_y, tw, 13, EPAPER_WHITE);
  epaper_rect(box_x, box_y, tw, 13, EPAPER_BLACK);
  gfx_text((uint16_t)(box_x + 3U), (uint16_t)(box_y + 4U), txt, 1, EPAPER_BLACK);

  uint16_t top    = 20U;
  uint16_t cbot   = (uint16_t)(h - 24U);    /* bottom of the shapes/lines area */

  /* Rectangles (outline and filled), bobbing up and down together. */
  uint16_t rect_y = (uint16_t)(top + bounce_pos(frame, 6U, 25U));
  epaper_rect     (4,  rect_y, 34, 14, EPAPER_BLACK);
  epaper_fill_rect(42, rect_y, 34, 14, EPAPER_BLACK);
  epaper_rect     (80, rect_y, 26, 14, EPAPER_BLACK);

  /* Circle: sweeps left and right across its own lane, clear of the rectangles. */
  uint16_t circ_min   = 110U;
  uint16_t circ_max   = (uint16_t)((w > (circ_min + 15U)) ? (w - 15U) : (circ_min + 1U));
  uint16_t circ_range = (uint16_t)(circ_max - circ_min);
  uint16_t circ_cx    = (uint16_t)(circ_min + bounce_pos(frame, circ_range, 47U));
  epaper_fill_circle(circ_cx, (uint16_t)(top + 7U), 7, EPAPER_BLACK);

  /* Lines: the horizontal line bobs vertically, the diagonal slides up and down
   * within its own band, and the vertical line sweeps across the circle's lane
   * out of step with it (different period and phase). */
  uint16_t hline_y = (uint16_t)(top + 18U + bounce_pos(frame, 6U, 17U));
  epaper_hline(4, hline_y, (uint16_t)(w - 8U), EPAPER_BLACK);
  uint16_t vline_x = (uint16_t)(circ_min + bounce_pos(frame + 20U, circ_range, 39U));
  epaper_vline(vline_x, top, (uint16_t)(cbot - top), EPAPER_BLACK);

  uint16_t diag_span = (uint16_t)(cbot - top - 8U);
  uint16_t diag_top  = (uint16_t)(top + bounce_pos(frame, 8U, 33U));
  for (uint16_t x = 4; x < (uint16_t)(w - 4U); x++)
  {
    uint16_t yy = (uint16_t)(diag_top + ((uint32_t)(x - 4U) * diag_span) / (w - 8U));
    epaper_set_pixel(x, yy, EPAPER_BLACK);
  }

  /* Marquee text: scrolls right to left, faster than the other elements.
   * Coordinates off either edge wrap through unsigned underflow;
   * epaper_set_pixel() drops anything outside the panel, so no clipping is
   * needed here (epaper_circle() relies on the same behavior). */
  uint16_t mq_w   = gfx_text_width(marquee, 1);
  uint32_t mq_tot = (uint32_t)w + mq_w;
  uint16_t mq_pos = (uint16_t)((frame * 5U) % mq_tot);
  uint16_t mq_x   = (uint16_t)((int32_t)w - (int32_t)mq_pos);
  gfx_text(mq_x, (uint16_t)(cbot + 4U), marquee, 1, EPAPER_BLACK);

  /* Box bouncing along the bottom lane; its position (mx) changes every frame. */
  epaper_fill_rect(mx, (uint16_t)(h - 10U), 8, 8, EPAPER_BLACK);
}

static void run_extremegfx(void)
{
  uint8_t  level = 0U, win_frames = 0U;
  uint32_t win_t0, fps_x10 = 0U, frame = 0U;
  uint16_t w = epaper_width();
  uint16_t mx_min = 4U, mx_max = (uint16_t)(w - 12U);
  uint16_t mx = mx_min;
  int8_t   mdir = 1;
  bool     quit = false;

  if (!epaper_extreme_begin())
  {
    board_log("extremegfx: unavailable (GDEY0213B74 / EPAPER_DISPLAY=1 only) or BUSY timeout");
    epaper_extreme_end();
    return;
  }
  board_log("extremegfx: start, level 1/%u", (unsigned)EPAPER_EXTREME_LEVELS);

  extremegfx_render(frame, mx, fps_x10);
  win_t0 = HAL_GetTick();

  while (!quit)
  {
    epaper_extreme_frame_start();                /* send this frame, start refresh */
    frame++;
    if (mx <= mx_min) mdir = 1; else if (mx >= mx_max) mdir = -1;
    mx = (uint16_t)(mx + mdir);
    extremegfx_render(frame, mx, fps_x10);       /* next frame, drawn during the refresh */

    event_t  ev = EV_NONE;
    uint32_t t0 = HAL_GetTick();
    while (epaper_extreme_busy())                /* the one wait the panel needs */
    {
      event_t e = input_poll();
      if (e != EV_NONE) ev = e;
      if ((HAL_GetTick() - t0) > APP_FPS_BUSY_TIMEOUT_MS) fatal("e-paper BUSY timeout in extreme-graphics test");
    }

    if (++win_frames >= MAXFPS_WINDOW_FRAMES)
    {
      uint32_t now = HAL_GetTick();
      uint32_t dt  = now - win_t0;
      if (dt == 0U) dt = 1U;
      fps_x10 = ((uint32_t)win_frames * 10000UL) / dt;
      board_log("extremegfx: level %u/%u (%lu MHz, N=%u): %lu.%lu fps",
                (unsigned)(level + 1U), (unsigned)EPAPER_EXTREME_LEVELS,
                (unsigned long)(epaper_extreme_spi_hz() / 1000000UL),
                (unsigned)epaper_extreme_level_frames(level),
                (unsigned long)(fps_x10 / 10U), (unsigned long)(fps_x10 % 10U));
      win_frames = 0U;
      win_t0 = now;
    }

    if (ev == EV_LONG || ev == EV_LEFT)
    {
      quit = true;
    }
    else if (ev != EV_NONE)                      /* next (faster) level, wraps to level 1 */
    {
      level = (uint8_t)((level + 1U) % EPAPER_EXTREME_LEVELS);
      if (!epaper_extreme_set_level(level)) fatal("e-paper BUSY timeout in extreme-graphics test");
      fps_x10 = 0U;
      win_frames = 0U;
      win_t0 = HAL_GetTick();
    }
  }

  epaper_extreme_end();                          /* normal SPI speed + full re-init on next update */
  board_log("extremegfx: stopped");
}

/* Panel Recovery -------------------------------------------------------------
 *
 * Alternates full-screen black and white using only epaper_clear() and
 * epaper_update(), the normal in-spec update path (never epaper_fast_*() or
 * epaper_extreme_*()). Driving every pixel fully to one extreme and then the
 * other with the panel's own waveform is the standard remedy for residual
 * ghosting after partial or out-of-spec updates.
 *
 * It may not clear every case: ghosting after long or repeated out-of-spec
 * drive can take more than one run to fade, and physical panel damage is not
 * repaired by refreshing.
 */
static void run_recovery(void)
{
  board_log("recovery: starting %u black/white flash cycles", (unsigned)RECOVERY_CYCLES);
  for (uint8_t i = 0; i < RECOVERY_CYCLES; i++)
  {
    epaper_clear(EPAPER_BLACK);
    show();
    epaper_clear(EPAPER_WHITE);
    show();
    board_log("recovery: cycle %u/%u done", (unsigned)(i + 1U), (unsigned)RECOVERY_CYCLES);
    if (input_poll() == EV_LONG)
    {
      board_log("recovery: cancelled by user");
      return;                                   /* panel is left white */
    }
  }
  board_log("recovery: finished");
}

/* STOP mode ------------------------------------------------------------------
 *
 * Shows a message, powers the display down (the image stays on the glass),
 * sleeps in STOP mode and waits for a rising edge on B1.
 */
static void enter_stop(void)
{
  epaper_clear(EPAPER_WHITE);
  draw_title("Sleeping (STOP)");
  gfx_text(4, (uint16_t)(GFX_CHAR_H * ui_scale() + 6U), "MCU in STOP, display off", 1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(GFX_CHAR_H * ui_scale() + 16U), "Press B1 to wake up", 1, EPAPER_BLACK);
  show();

  board_log("Entering STOP; press B1 to wake");
  epaper_power_off();
  board_led_green(false);
  board_led_red(false);

#if APP_STOP_DISABLE_DEBUG
  HAL_DBGMCU_DisableDBGStopMode();
#endif
#if APP_STOP_ULTRA_LOW_POWER
  HAL_PWREx_EnableUltraLowPower();
  HAL_PWREx_EnableFastWakeUp();
#endif

  board_arm_wake();
  do
  {
    HAL_SuspendTick();
    HAL_PWR_EnterSTOPMode(PWR_LOWPOWERREGULATOR_ON, PWR_STOPENTRY_WFI);
    SystemClock_Config();                 /* the system clock runs from MSI after STOP; restore the PLL configuration */
    HAL_ResumeTick();
  } while (!board_wake_flag());
  board_disarm_wake();

  uint32_t t0 = HAL_GetTick();            /* wait (max 2 s) for the wake-up press to end */
  while (board_button_pressed() && (HAL_GetTick() - t0) < 2000U) { }

  board_log("Woke from STOP");
  if (!epaper_power_on()) fatal("e-paper did not come back after STOP");

  epaper_clear(EPAPER_WHITE);
  draw_title("Awake!");
  gfx_text(4, (uint16_t)(GFX_CHAR_H * ui_scale() + 6U), "Woken by B1. Display was", 1, EPAPER_BLACK);
  gfx_text(4, (uint16_t)(GFX_CHAR_H * ui_scale() + 16U), "unpowered while asleep.", 1, EPAPER_BLACK);
  show();
  HAL_Delay(1500);
}

/* Switch to page p and request a redraw. */
static void go(page_t p)
{
  page = p;
  redraw = true;
  disp_stage = 0;
  board_log("page %u", (unsigned)p);
}

/* Public functions ---------------------------------------------------------*/

void app_init(void)
{
  board_log("");
  board_log("STM32L0538-DISCO showcase");
  board_log("E-paper build: EPAPER_DISPLAY=%u -> %s", epaper_display_id(), epaper_name());

  if (!epaper_init()) fatal("epaper_init failed (BUSY stuck) - wrong display selected?");
  draw_splash();
  show();
  board_led_green(true); HAL_Delay(150); board_led_green(false);   /* blink: first refresh succeeded */

  touch_ok = touch_init();
  board_log("touch: %s", touch_ok ? "OK" : "no counts (check TSC config)");

  sel = 0;
  go(PAGE_MENU);
}

void app_run(void)
{
  event_t ev = input_poll();

  switch (page)
  {
    case PAGE_MENU:
      if (ev == EV_SHORT)                        { sel = (uint8_t)((sel + 1U) % MENU_COUNT); redraw = true; }
      else if (ev == EV_LONG)                    { go(menu_page[sel]); }
      break;

    case PAGE_TOUCH:
    {
      const touch_state_t *t = touch_state();
      board_led_green(t->zone >= 0);
      if (ev == EV_SHORT || ev == EV_LONG)       { board_led_green(false); go(PAGE_MENU); }
      else if (t->zone != shown_zone && (HAL_GetTick() - last_touch_draw) >= APP_TOUCH_REDRAW_MS)
      {
        redraw = true;
        last_touch_draw = HAL_GetTick();
      }
      break;
    }

    case PAGE_LEDS:
      if (ev == EV_SHORT || ev == EV_MID)
      {
        led_mode = (uint8_t)((led_mode + 1U) & 3U);
        board_led_green((led_mode & 1U) != 0U);
        board_led_red((led_mode & 2U) != 0U);
        redraw = true;
      }
      else if (ev == EV_LONG || ev == EV_LEFT)   { board_led_green(false); board_led_red(false); led_mode = 0; go(PAGE_MENU); }
      break;

    case PAGE_STOP:
      if (ev == EV_SHORT || ev == EV_MID)        { enter_stop(); go(PAGE_STOP); }
      else if (ev == EV_LONG || ev == EV_LEFT)   { go(PAGE_MENU); }
      break;

    case PAGE_INFO:
      if (ev != EV_NONE)                         { go(PAGE_MENU); }
      break;

    case PAGE_MAXFPS:
      if (ev == EV_LONG || ev == EV_LEFT)        { go(PAGE_MENU); }
      else if (ev != EV_NONE)                    { run_maxfps(); go(PAGE_MENU); }
      break;

    case PAGE_EXTREMEFPS:
      if (ev == EV_LONG || ev == EV_LEFT)        { go(PAGE_MENU); }
      else if (ev != EV_NONE)                    { run_extremefps(); go(PAGE_MENU); }
      break;

    case PAGE_EXTREMEGFX:
      if (ev == EV_LONG || ev == EV_LEFT)        { go(PAGE_MENU); }
      else if (ev != EV_NONE)                    { run_extremegfx(); go(PAGE_MENU); }
      break;

    case PAGE_RECOVERY:
      if (ev == EV_LONG || ev == EV_LEFT)        { go(PAGE_MENU); }
      else if (ev != EV_NONE)                    { run_recovery(); go(PAGE_MENU); }
      break;

    case PAGE_DISPTEST:                          /* Example 1 -> 2 -> ... -> 6 -> menu */
      if (ev == EV_LONG || ev == EV_LEFT)        { go(PAGE_MENU); }
      else if (ev != EV_NONE)
      {
        if (disp_stage + 1U < DISP_STAGE_COUNT)
        {
          disp_stage++;
          redraw = true;
        }
        else                                     { go(PAGE_MENU); }
      }
      break;
  }

  if (redraw)
  {
    redraw = false;
    if (page == PAGE_DISPTEST && disp_stage != 0U)
    {
      static void (*const gray_draw[DISP_STAGE_COUNT])(void) =
        { NULL, draw_example2_4gray, draw_example3_16gray, draw_example4_gradient,
          draw_example5_16smooth, draw_example6_smooth };
      bool ok = (disp_stage >= 4U)
                  ? epaper_update_gray16(gray_draw[disp_stage], g16_max_frames())
                  : epaper_update_gray(gray_draw[disp_stage]);
      if (!ok) fatal("e-paper BUSY timeout on gray update");
    }
    else
    {
      draw_page();
      show();
    }
  }
  HAL_Delay(2);
}
